// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.3.0
// source: close.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloseMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *CloseMsg) Reset() {
	*x = CloseMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_close_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseMsg) ProtoMessage() {}

func (x *CloseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_close_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseMsg.ProtoReflect.Descriptor instead.
func (*CloseMsg) Descriptor() ([]byte, []int) {
	return file_close_proto_rawDescGZIP(), []int{0}
}

func (x *CloseMsg) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CloseAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseAnswer) Reset() {
	*x = CloseAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_close_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAnswer) ProtoMessage() {}

func (x *CloseAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_close_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAnswer.ProtoReflect.Descriptor instead.
func (*CloseAnswer) Descriptor() ([]byte, []int) {
	return file_close_proto_rawDescGZIP(), []int{1}
}

var File_close_proto protoreflect.FileDescriptor

var file_close_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x22, 0x0a, 0x08, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x4d, 0x73,
	0x67, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x0d, 0x0a, 0x0b, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_close_proto_rawDescOnce sync.Once
	file_close_proto_rawDescData = file_close_proto_rawDesc
)

func file_close_proto_rawDescGZIP() []byte {
	file_close_proto_rawDescOnce.Do(func() {
		file_close_proto_rawDescData = protoimpl.X.CompressGZIP(file_close_proto_rawDescData)
	})
	return file_close_proto_rawDescData
}

var file_close_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_close_proto_goTypes = []interface{}{
	(*CloseMsg)(nil),    // 0: protos.CloseMsg
	(*CloseAnswer)(nil), // 1: protos.CloseAnswer
}
var file_close_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_close_proto_init() }
func file_close_proto_init() {
	if File_close_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_close_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_close_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_close_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_close_proto_goTypes,
		DependencyIndexes: file_close_proto_depIdxs,
		MessageInfos:      file_close_proto_msgTypes,
	}.Build()
	File_close_proto = out.File
	file_close_proto_rawDesc = nil
	file_close_proto_goTypes = nil
	file_close_proto_depIdxs = nil
}
